-- One-time setup for a fresh external Postgres environment (e.g. the LAB
-- cluster's Postgres at 192.168.0.148, driven by the "postgresdb" Harness
-- connector). Postgres has no "CREATE DATABASE IF NOT EXISTS", and Flyway
-- only manages schema *within* a database - it can't create the database
-- itself - so this has to be run by hand, once per environment, before the
-- app's first deploy there.
--
-- Run with psql so the \c reconnect below works, e.g.:
--   psql -h 192.168.0.148 -U admin -d postgres -f scripts/bootstrap-lab-db.sql
-- (connect to any existing database first, such as the default "postgres"
-- one - you can't run CREATE DATABASE while connected to the db you're
-- creating). If you're using a different client (pgAdmin, DBeaver, etc.),
-- run the CREATE DATABASE statement, then open a new connection to
-- mockingbirdbank and run the CREATE TABLE statements there instead.
--
-- After this runs, the app's flyway.baseline-on-migrate: true (see
-- application.yml) takes over automatically: on first boot against this
-- now-non-empty schema, Flyway baselines at version 1 (the default,
-- matching V1) instead of re-running it, so nothing further is needed here.
--
-- The CREATE TABLE statements below are a literal copy of
-- src/main/resources/db/migration/V1__init_schema.sql (not a psql \i
-- include, so this script is portable to environments where only this
-- file - not the whole repo - is available). V1 is a frozen migration
-- (see its own header comment) so this copy should never need to drift.

CREATE DATABASE mockingbirdbank;

\c mockingbirdbank

CREATE TABLE account_holder (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE account (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holder_id      BIGINT NOT NULL REFERENCES account_holder (id),
    account_number VARCHAR(255) NOT NULL UNIQUE,
    account_type   VARCHAR(255) NOT NULL,
    nickname       VARCHAR(255),
    balance        NUMERIC(14, 2) NOT NULL,
    opened_at      DATE NOT NULL
);

CREATE TABLE transaction (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT NOT NULL REFERENCES account (id),
    posted_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    description VARCHAR(255) NOT NULL,
    category    VARCHAR(255),
    amount      NUMERIC(14, 2) NOT NULL
);

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    holder_id     BIGINT NOT NULL UNIQUE REFERENCES account_holder (id)
);
