-- Baseline schema, capturing exactly what Hibernate's ddl-auto=update had
-- already been creating. From here on, schema changes go in new versioned
-- migrations (V2__..., V3__...) - never edit a migration that may have
-- already run anywhere, including a teammate's laptop.

CREATE TABLE account_holder (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE account (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holder_id      BIGINT NOT NULL REFERENCES account_holder (id),
    account_number VARCHAR(255) NOT NULL UNIQUE,
    account_type   VARCHAR(255) NOT NULL,
    nickname       VARCHAR(255),
    balance        NUMERIC(14, 2) NOT NULL,
    opened_at      DATE NOT NULL
);

CREATE TABLE transaction (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT NOT NULL REFERENCES account (id),
    posted_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    description VARCHAR(255) NOT NULL,
    category    VARCHAR(255),
    amount      NUMERIC(14, 2) NOT NULL
);

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    holder_id     BIGINT NOT NULL UNIQUE REFERENCES account_holder (id)
);
